---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age19hyy0u6zq63mqtdpsr57fyn74v7xql4ccdgs45gwx9svx32f03kqefq224
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age19hyy0u6zq63mqtdpsr57fyn74v7xql4ccdgs45gwx9svx32f03kqefq224
