# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:10EC/0/ZeUGwxpwkRG4xiISemUTfrw==,iv:7RPGbuEq36za9N7FLqL8gNWqVleNrivIM1irP03uVbU=,tag:/Q030YnONSAZF4Oerg/vyQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:xZ/yCPVeB2Oly9I50RNmOfpnJQF41fHAZ7tRcO+ljtPvYLU86A==,iv:gQm5mQ9aHds5ashVKENm6snrqJ6yMr1EJ4Rkt7pJGCc=,tag:WDHbo/Hu0e4rZd0rlqfESg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:h6zGmSunVAaH11pT3EHvGoY=,iv:GAz0icaUP07xC4Egac+1Cta+r7+0Iq6YGgutuLIglOI=,tag:mCZXLKxB7+MYTiSnZu5msA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hyy0u6zq63mqtdpsr57fyn74v7xql4ccdgs45gwx9svx32f03kqefq224
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsd09WKzIweVk2Lzh4QzNS
            UHltQzZCNTJoRTdjenNxTExHaTQ0NXZvdldRCkNHNTdvVkNXUFNGNDVxNGNyaEoz
            WnVHdHppVGdsbnBZcGVJV3RvTkRrTzQKLS0tIDd5cGdHR1I5WHpVeUFyL0tXUm8w
            VGtSblc5N2dZNko3MTJWc2g4dHV4Zk0KdxESH0Ozd/MGkj+f04dfOSuqRqU7MtSq
            bYZPIqM9cz78R4fEoXWho7/5fjA4jcZJjrgfExbJ2s09SUrKbup3xA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-04T18:21:34Z"
    mac: ENC[AES256_GCM,data:fKDJkP0zAe+zXZE7zVBW3OHX/F4TzV3s07FhnmdBV8k7U3DVLdkCUobOWixcl/YtbkDbC1T9Ayv49JhnWLOnumRMyE88D4i/qfI89q1tBZz1QHtL2COxq3pYKisB0WTMGDcWIfCwCCHiMWpZBinrXi3G/J9cw6I3sPkZy3LpBso=,iv:e7iiCDBC8hB4ID/6PbWWiHF91VVv6gXK6XmGatQ4QXo=,tag:4dl/DudmaJvB9tW3bREPDw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
