---
kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 10.0.0.155
        k8s-3:
          ansible_host: 10.0.0.158
    worker:
      hosts:
        k8s-1:
          ansible_host: 10.0.0.156
        k8s-2:
          ansible_host: 10.0.0.157
