# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:Wei5TImDd7wPh1lJcU06NSVZATryfsaLErZcTzvIizpByTHYZw==,iv:o3/Ef2SDDBz/zcqoCPARa7a/Hl5MRnTnr8UaYOryD2k=,tag:0LpSiMnxqGuk8cD9chTYGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hyy0u6zq63mqtdpsr57fyn74v7xql4ccdgs45gwx9svx32f03kqefq224
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYnlqY0tYTnh6NU81TlJD
            TzFFRGtBbnZvQnE3UmF5ZFdWQW0zZStvMTJVCkpEZDg3UzlXMy9ueEJ4ZXVBNWIx
            MlM4Q0FHU3pxQUpRNXZMUXF1Mzloc2MKLS0tIC9kaHhZbnBwSmd2cG0zbHlzamtW
            ekhDMGU5bHNSaEEzZWNsNGY1cDloQ1UKPp/V1x2YYUqYRY7hOQ7nDEb3U/s6yVmO
            PtOBwsMmIrkAuqdqLaiEh7iBEImLY1NFhs2TfAvq9MC/D8mkRbE22g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-04T18:21:34Z"
    mac: ENC[AES256_GCM,data:nOK3J8TWVGlGIaVvK95z7KUOsYgmBQdszgtYFAOU+ZFHu9L8eJYFSq9j2OcRI3vLw1QAfgMIJLNN4qbTgx54Ju6/gFkqFN+HmjbZo/LWqWjZwPztQ/GU7XBG1xObCWxOnqCUdeHUjvs1/4UKlOtc061lntghZ5qE+M3BzgoJjyE=,iv:J5C65+WFKSDKOT4DHL33y8q8bYIgXEVuzlM2Roquum4=,tag:vboynh8DrxSVfx/oh7EBFA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
