---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Sao_Paulo
  METALLB_LB_RANGE: 10.0.0.211-10.0.0.245
  METALLB_K8S_GATEWAY_ADDR: 10.0.0.211
  METALLB_INGRESS_ADDR: 10.0.0.212
