kind: Secret
ansible_user: ENC[AES256_GCM,data:a5L1Xw==,iv:C6JGKCEb3wkwtxwid31mc5B0eKKW67fIZP13kfEI8Do=,tag:elYsBZju10ZPAXLs5Lakog==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:jtgljA2JEDzkFpbnJtwl,iv:P9EMLOf8OJBWO2nZFouyrErolMI+VeN3Kl6Fwi+CJeU=,tag:5x64vFLpLqfvxLUXeykabA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hyy0u6zq63mqtdpsr57fyn74v7xql4ccdgs45gwx9svx32f03kqefq224
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpcWZLY2lkbHlEalkvWWJS
            YW5kNzlOMGJHMlhQVEdxSTBKc2V2WWFEV0JRCmlQc3l4TTAwcmFyb1A4SkVRQmMy
            TnI1dlJqNHhQZSt0elJVbHR4elBDNUUKLS0tIDNpV0NDTzJLekQyTTh5S09IUldO
            eXdUbklGcWVjV0pKVVAvc2o0OWpSaUUKQZNkPZQcd0v/WhjJCxOj2UHA5UgZgJpl
            aqOOq5IldA96Xj3KEmlelqylX5p5ZMkdjQa4INNvqrpWl5tk/7EK9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-04T18:21:35Z"
    mac: ENC[AES256_GCM,data:/7mScaAQsh/J3ur/xYhm3le8amoZdCy1QjHIh60GuU8kr7Fxy7eGBgZgtHzq7lmeJIuUzu0oERPzmOvYXBNUV9TCTupn6l2ajbTgmi6/3/eW65xlAXpdx73XKi/8uvK1bYvhRuV7NFOVruZW59ZKJWYoguSrmYduq3FhPhnZjyc=,iv:3SgnIBV1D9OazF3OmuRoLQQeRxBeKSXru1WBSiCD6Uc=,tag:2qkiyudI0+fylCSSi6o5Vw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
