kind: Secret
ansible_user: ENC[AES256_GCM,data:rpHOUw==,iv:XNBLsweIwwN4jhN1nWvGOAyj+j37qUvbD2ze1SJ9/CI=,tag:Qsy+SOSZP14NrSd1x3f2Rw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:TGhq9DXmsKYeznMMRJa4,iv:U8ikv+97j6Hap/BS0+YEkt7GgWtcM27uvZ06+f3wKq4=,tag:B1fG/4yGcQXwzRt0zBl+Pg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19hyy0u6zq63mqtdpsr57fyn74v7xql4ccdgs45gwx9svx32f03kqefq224
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMS9TVlVOL3QyTEQ5OGZJ
            N1NsRklEK3I2bWJSaGxXMHBxM3VISFpZVEUwCjU1dHhBVkFqSXF4SzdKYmlJMTlX
            T2VBclRYTHNBNEhFL2t3cGtXb2ZKa0EKLS0tIHUySWhVV0ZZNkVOS3JtM0hoWXJN
            WXNKN3ZjeWQzVEFVRTVoT0g0TVdXUEkK0CO0j5ZouTKtWLQ+vgtRq3RUZ7F+5a/x
            gpgAnfLLtG4J0SZY9KFlpw88GIfB6fv8p1HzW33tzM6H24aki0t89Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-03T22:15:59Z"
    mac: ENC[AES256_GCM,data:sGeRv2w2IIJEEj9pTFEOjWGwaExPIaMbrutIohc51NRaLQdY2Wbs99Bi5ynI1QC/Ln/17rrROcRhSjNaW1klvLGdzJysx21PzV9DCd2MrDipYlq7nPihNqyhR9RVTnex4/6OPxzNdDNG4VpOH6dOAIHnL+0pYlJy+l7+j7dJeAI=,iv:IOLL1UuDs/aUvv982vz1Ue5zLstQBtgGzGqjenBLNnQ=,tag:QTqlpiTS024KvBV3P4U0nA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
