---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 2
      reclaimPolicy: Retain
    defaultSettings:
      # backupstorePollInterval: 300
      # backupTarget: nfs://${NFS_SERVER}:/volume1/kubernetes/LonghornBackup
      createDefaultDiskLabeledNodes: true
      defaultDataLocality: best-effort
      defaultReplicaCount: 2
      defaultLonghornStaticStorageClass: longhorn
    ingress:
      enabled: true
      path: /
      tls: true
      tlsSecret: longhorn-tls
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: SECRET_HTPASSWD_NGINX_BASIC
        nginx.ingress.kubernetes.io/auth-realm: "Enter your credentials"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        external-dns/is-public: "true"
        hajimari.io/enable: "true"
        hajimari.io/icon: "video-input-antenna"
      host: "longhorn.${SECRET_DOMAIN}"
